version: '3.7'

services:
  01people-base-laravel-composer:
    container_name: 01people-base-laravel-composer
    image: composer:2.0
    stdin_open: true
    command: ["composer", "install"]
    volumes:
      - .:/app

  01people-base-laravel-db:
    image: postgres:13.1
    container_name: 01people-base-laravel-db
    tty: true
    restart: always
    env_file:
      - .env
    ports:
      - '127.0.0.1:3333:5432'
    volumes:
      - 01people-base-laravel:/var/lib/postgresql/data

  01people-base-laravel-app:
    container_name: 01people-base-laravel-app
    build:
      dockerfile: ./Dockerfile
      context: ./
    depends_on:
      - 01people-base-laravel-db
    volumes:
      - .:/var/www/app/

  01people-base-laravel-nginx:
    image: nginx:1.19
    container_name: 01people-base-laravel-nginx
    ports:
      - '127.0.0.1:8081:80'
    volumes:
      - .:/var/www/app/
      - ./etc/nginx/sites-enabled/default:/etc/nginx/conf.d/default.conf
    depends_on:
      - 01people-base-laravel-app

volumes:
  01people-base-laravel:
    name: 01people-base-laravel-db
